### ISSUE TITLE
Potential XSS Vulnerability

### ISSUE THREAD

**Issue by KimChoJapFan** [nsuchy/PHPShare#2]
Having the ability to upload HTML files will create the ability for users to upload HTML with inline JS unless you specify to have the [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) headers set to ignore all inline scripts.

**Comment by nsuchy** [comment]
Hi @KimChoJapFan that's better managed at the nginx or apache2 level. I could update the README.md file to specify that.

**Comment by KimChoJapFan** [comment]
That'll be great; I've made a repository for Nginx configs that goes into the secure headers and I suppose I can also translate those Nginx configs to Apache, Lighttpd, and Caddy (for the strange folks that use Caddy).
